### ISSUE TITLE
I like how you chose to check for errors throughout your code

### ISSUE THREAD

**Issue by jzhu01** [mrrichardasmith/Jamming#3]
Seen here: https://github.com/mrrichardasmith/Jamming/blob/4d79727a385e093249e1554182b265245de47b04/src/util/Spotify.js#L31-L64
I thought this was very effective and nicely done. It shows you understand what is occurring at each layer of the promise. Although it might be a bit overdone, as a user might not check all those errors, or could be confused.

**Comment by mrrichardasmith** [comment]
Note to self, clean code of anything not needed by the users
