### ISSUE TITLE
Suggestion - else is not necessary here

### ISSUE THREAD

**Issue by jzhu01** [mrrichardasmith/Jamming#5]
Seen here: https://github.com/mrrichardasmith/Jamming/blob/4d79727a385e093249e1554182b265245de47b04/src/Components/Track/Track.js#L18
Since the return will exit out of the function, if the code makes it that far then it must have not met the if conditions. There's no need to explicitly write else here.

**Comment by mrrichardasmith** [comment]
Note to self, no unnecessary else statements.
