### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [mrrichardasmith/Jamming#7]
Adding the ability to trigger the search function by pressing enter button will indeed make the app faster to navigate. Great choice using unicode value '13' rather than the value ‘Enter’. The note for instructors will be forwarded to the product team for review.

The technical design you have layed out for the enter key is correct, following your instructions, I would have 
```
  enterSearch(event) {
    if(event.keyCode === 13) {
      this.search();
    }
}
```
and
`<input onKeyDown={this.enterSearch}/>`

**Comment by mrrichardasmith** [comment]
Thanks for the feedback. I expect this will come up a lot in my career. 

Best 

Richard
